# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  db:
    image: postgres
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ale123
      POSTGRES_DB: autenticacao
    ports:
      - 5432:5432
    networks:
      - rede_autenticador
  autenticador:
    image: autenticador
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5085:5085
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - db
    networks:
      - rede_autenticador

networks:
  rede_autenticador: 
    driver: bridge